name: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)

variables:
  BuildConfiguration: 'Release'
  RepoName: 'Songhay.Social'

trigger:
  batch: 'false'
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - $(RepoName).Activities.Tests/*
    - $(RepoName).Repository.Tests/*
    - $(RepoName).Shell.Tests/*
    - $(RepoName).Tests/*

resources:
- repo: self

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.2.402'
  inputs:
    version: 2.2.402

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: downloadsSecureFile@0
  inputs:
    fileInput: 'ad50f588-a3c3-4588-9493-25f8928df05d'
    targetPath: $(RepoName).Web
    targetName: 'app-settings.songhay-system.json'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test [Web]'
  inputs:
    command: test
    projects: '**/$(RepoName).Web.Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
